# This file is generated by homebrew/prepare.mjs in johncarmack1984/glslint
# and pushed here by that repo's release workflow. Do not edit it by hand — edit
# the generator instead; a hand edit is overwritten on the next release.
class Glslint < Formula
  desc "GLSL checker and language server for luma.gl/deck.gl shaders"
  homepage "https://github.com/johncarmack1984/glslint"
  version "0.7.0"
  license any_of: ["MIT", "Apache-2.0"]

  # glslint shells out to glslangValidator (the Khronos GLSL reference compiler)
  # to validate assembled shaders, so it is a runtime dependency, not just a
  # build one.
  depends_on "glslang"

  on_macos do
    on_arm do
      url "https://github.com/johncarmack1984/glslint/releases/download/v0.7.0/glslint-aarch64-apple-darwin"
      sha256 "6d481a3d0e4d34ff206d741add962318f1acaf903a6a64d24ec842ab556b1118"
    end
    on_intel do
      url "https://github.com/johncarmack1984/glslint/releases/download/v0.7.0/glslint-x86_64-apple-darwin"
      sha256 "5e272c48ac5528c787433ba661edcedb9ad494d2ffb130ddcb9966e8a34b98e0"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/johncarmack1984/glslint/releases/download/v0.7.0/glslint-x86_64-unknown-linux-gnu"
      sha256 "0fdf5bdb990e7fc623ea42dba6f2308bb2cd7e6a061d170ac1725b038c2480f7"
    end
  end

  def install
    # Exactly one asset is downloaded per platform; install it under the plain
    # command name.
    bin.install Dir["glslint-*"].first => "glslint"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/glslint --version")
  end
end
