# This file is generated by homebrew/prepare.mjs in johncarmack1984/glslint
# and pushed here by that repo's release workflow. Do not edit it by hand — edit
# the generator instead; a hand edit is overwritten on the next release.
class Glslint < Formula
  desc "GLSL checker and language server for luma.gl/deck.gl shaders"
  homepage "https://github.com/johncarmack1984/glslint"
  version "0.8.0"
  license any_of: ["MIT", "Apache-2.0"]

  # glslint shells out to glslangValidator (the Khronos GLSL reference compiler)
  # to validate assembled shaders, so it is a runtime dependency, not just a
  # build one.
  depends_on "glslang"

  on_macos do
    on_arm do
      url "https://github.com/johncarmack1984/glslint/releases/download/v0.8.0/glslint-aarch64-apple-darwin"
      sha256 "20f9ec11271ab94b51f458613434b19ca5e0fd78031b856156afcc63d8e29ab0"
    end
    on_intel do
      url "https://github.com/johncarmack1984/glslint/releases/download/v0.8.0/glslint-x86_64-apple-darwin"
      sha256 "7fc2a1876d79e1886413dc0b2c704be37401ecd222856cd200ae0c5e1d7d2edc"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/johncarmack1984/glslint/releases/download/v0.8.0/glslint-x86_64-unknown-linux-gnu"
      sha256 "58c249cf72bb7c8b3ab9dca733d7928456885174eda79041e32a18d77684146b"
    end
  end

  def install
    # Exactly one asset is downloaded per platform; install it under the plain
    # command name.
    bin.install Dir["glslint-*"].first => "glslint"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/glslint --version")
  end
end
