# This file is generated by homebrew/prepare.mjs in johncarmack1984/glslint
# and pushed here by that repo's release workflow. Do not edit it by hand — edit
# the generator instead; a hand edit is overwritten on the next release.
class Glslint < Formula
  desc "GLSL checker and language server for luma.gl/deck.gl shaders"
  homepage "https://github.com/johncarmack1984/glslint"
  version "0.8.1"
  license any_of: ["MIT", "Apache-2.0"]

  # glslint shells out to glslangValidator (the Khronos GLSL reference compiler)
  # to validate assembled shaders, so it is a runtime dependency, not just a
  # build one.
  depends_on "glslang"

  on_macos do
    on_arm do
      url "https://github.com/johncarmack1984/glslint/releases/download/v0.8.1/glslint-aarch64-apple-darwin"
      sha256 "401490333f44c802aa41355b318cf90a43ab692c79dde38e6265936f632ec496"
    end
    on_intel do
      url "https://github.com/johncarmack1984/glslint/releases/download/v0.8.1/glslint-x86_64-apple-darwin"
      sha256 "9e032e117d3c65b229a3d117e9fdc62e46bb87b394a8ddba3a5eeefd901f809c"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/johncarmack1984/glslint/releases/download/v0.8.1/glslint-x86_64-unknown-linux-gnu"
      sha256 "0c2c205817ddf64f63c8d73d8fadf2b830593f57fa20cbaac7d2f84eaf24a117"
    end
  end

  def install
    # Exactly one asset is downloaded per platform; install it under the plain
    # command name.
    bin.install Dir["glslint-*"].first => "glslint"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/glslint --version")
  end
end
